name: Check Before Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check w/o SNAPSHOT for release
      run: grep "<version>" pom.xml | head -1 | grep -v SNAPSHOT
